name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
        coverage: pcov
        tools: phpunit:9.1.4

    - name: Install dependencies
      run: composer install --prefer-dist

    - name: Run tests
      run: vendor/bin/phpunit