name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    build:

      runs-on: ${{ matrix.operating-system }}
      strategy:
        matrix:
          operating-system: [ubuntu-latest, ubuntu-16.04]
          php: [5.6, 7.0, 7.1, 7.2, 7.3]
      name: PHP ${{ matrix.php }} sample
      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          tools: phpunit:9.1.4

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run tests
        run: php${{ matrix.php }} vendor/bin/phpunit